-- AlterTable
ALTER TABLE "User" ADD COLUMN "dailyReportEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "dailyReportHour" INTEGER NOT NULL DEFAULT 22;
ALTER TABLE "User" ADD COLUMN "dailyReportMinute" INTEGER NOT NULL DEFAULT 0;
